traits_dictionary = {
    'AAo max area (mm2)':'AAo_max_area', 
    'AAo min area (mm2)': 'AAo_min_area',
    'AAo distensibility (10-3 mmHg-1)': 'AAo_distensibility',
    'DAo max area (mm2)': 'DAo_max_area',
    'DAo min area (mm2)': 'DAo_min_area',
    'DAo distensibility (10-3 mmHg-1)': 'DAo_distensibility',
    'LAV max (mL)': 'LAV_max', 
    'LAV min (mL)': 'LAV_min', 
    'LASV (mL)': 'LASV',
    'LAEF (%)': 'LAEF',
    'RAV max (mL)': 'RAV_max',
    'RAV min (mL)': 'RAV_min',
    'RASV (mL)': 'RASV',
    'RAEF (%)': 'RAEF',
    'Ell_1 (%)': 'Ell_1',
    'Ell_2 (%)': 'Ell_2',
    'Ell_3 (%)': 'Ell_3',
    'Ell_4 (%)': 'Ell_4',
    'Ell_5 (%)': 'Ell_5',
    'Ell_6 (%)': 'Ell_6',
    'Ell_Global (%)': 'Ell_Global', 
    'Ecc_AHA_1 (%)': 'Ecc_AHA_1',
    'Ecc_AHA_2 (%)': 'Ecc_AHA_2',
    'Ecc_AHA_3 (%)': 'Ecc_AHA_3',
    'Ecc_AHA_4 (%)': 'Ecc_AHA_4',
    'Ecc_AHA_5 (%)': 'Ecc_AHA_5',
    'Ecc_AHA_6 (%)': 'Ecc_AHA_6',
    'Ecc_AHA_7 (%)': 'Ecc_AHA_7',
    'Ecc_AHA_8 (%)': 'Ecc_AHA_8',
    'Ecc_AHA_9 (%)': 'Ecc_AHA_9',
    'Ecc_AHA_10 (%)': 'Ecc_AHA_10',
    'Ecc_AHA_11 (%)': 'Ecc_AHA_11',
    'Ecc_AHA_12 (%)': 'Ecc_AHA_12',
    'Ecc_AHA_13 (%)': 'Ecc_AHA_13',
    'Ecc_AHA_14 (%)': 'Ecc_AHA_14',
    'Ecc_AHA_15 (%)': 'Ecc_AHA_15',
    'Ecc_AHA_16 (%)': 'Ecc_AHA_16',
    'Ecc_Global (%)': 'Ecc_Global',
    'Err_AHA_1 (%)': 'Err_AHA_1',
    'Err_AHA_2 (%)': 'Err_AHA_2',
    'Err_AHA_3 (%)': 'Err_AHA_3',
    'Err_AHA_4 (%)': 'Err_AHA_4',
    'Err_AHA_5 (%)': 'Err_AHA_5',
    'Err_AHA_6 (%)': 'Err_AHA_6',
    'Err_AHA_7 (%)': 'Err_AHA_7',
    'Err_AHA_8 (%)': 'Err_AHA_8',
    'Err_AHA_9 (%)': 'Err_AHA_9',
    'Err_AHA_10 (%)': 'Err_AHA_10',
    'Err_AHA_11 (%)': 'Err_AHA_11',
    'Err_AHA_12 (%)': 'Err_AHA_12',
    'Err_AHA_13 (%)': 'Err_AHA_13',
    'Err_AHA_14 (%)': 'Err_AHA_14',
    'Err_AHA_15 (%)': 'Err_AHA_15',
    'Err_AHA_16 (%)': 'Err_AHA_16',
    'Err_Global (%)': 'Err_Global',
    'LVEDV (mL)': 'LVEDV',
    'LVESV (mL)': 'LVESV',
    'LVSV (mL)':    'LVSV',
    'LVEF (%)': 'LVEF',
    'LVCO (L/min)': 'LVCO',
    'LVM (g)': 'LVM',
    'RVEDV (mL)': 'RVEDV',
    'RVESV (mL)': 'RVESV',
    'RVSV (mL)': 'RVSV',
    'RVEF (%)': 'RVEF',
    'WT_AHA_1 (mm)': 'WT_AHA_1',
    'WT_AHA_2 (mm)': 'WT_AHA_2',
    'WT_AHA_3 (mm)': 'WT_AHA_3',
    'WT_AHA_4 (mm)': 'WT_AHA_4',
    'WT_AHA_5 (mm)': 'WT_AHA_5',
    'WT_AHA_6 (mm)': 'WT_AHA_6',
    'WT_AHA_7 (mm)':    'WT_AHA_7',
    'WT_AHA_8 (mm)': 'WT_AHA_8',
    'WT_AHA_9 (mm)': 'WT_AHA_9',
    'WT_AHA_10 (mm)':   'WT_AHA_10',
    'WT_AHA_11 (mm)':   'WT_AHA_11',
    'WT_AHA_12 (mm)':   'WT_AHA_12',
    'WT_AHA_13 (mm)':  'WT_AHA_13',
    'WT_AHA_14 (mm)':   'WT_AHA_14',
    'WT_AHA_15 (mm)':   'WT_AHA_15',
    'WT_AHA_16 (mm)':   'WT_AHA_16',
    'WT_Global (mm)':   'WT_Global',
    'WT_Max_AHA_1 (mm)': 'WT_Max_AHA_1',
    'WT_Max_AHA_2 (mm)': 'WT_Max_AHA_2',
    'WT_Max_AHA_3 (mm)': 'WT_Max_AHA_3',
    'WT_Max_AHA_4 (mm)': 'WT_Max_AHA_4',
    'WT_Max_AHA_5 (mm)': 'WT_Max_AHA_5',
    'WT_Max_AHA_6 (mm)': 'WT_Max_AHA_6',
    'WT_Max_AHA_7 (mm)':    'WT_Max_AHA_7',
    'WT_Max_AHA_8 (mm)': 'WT_Max_AHA_8',
    'WT_Max_AHA_9 (mm)': 'WT_Max_AHA_9',
    'WT_Max_AHA_10 (mm)':   'WT_Max_AHA_10',
    'WT_Max_AHA_11 (mm)':   'WT_Max_AHA_11',
    'WT_Max_AHA_12 (mm)':   'WT_Max_AHA_12',
    'WT_Max_AHA_13 (mm)':  'WT_Max_AHA_13',
    'WT_Max_AHA_14 (mm)':   'WT_Max_AHA_14',
    'WT_Max_AHA_15 (mm)':   'WT_Max_AHA_15',
    'WT_Max_AHA_16 (mm)':   'WT_Max_AHA_16',
    'WT_Max_Global (mm)':   'WT_Max_Global',
    'Age at MRI (year)': 'age_at_MRI', 
    'Weight (kg)':  'Weight_at_MRI',
    'Height (m)':   'Height', 
    'BMI (kg m-2)': 'BMI', 
    'Body surface area (m2)': 'BSA', 
    'Systolic blood pressure (mmHg)': 'SBP_at_MRI',
    'Diastolic blood pressure (mmHg)': 'DBP_at_MRI', 
    'Mean arterial pressure (mmHg)': 'MAP_at_MRI'
}

# BSA = 0.20247 * (weight^0.425) * (height^0.725), the Mosteller formula calculated using weight pre-imaging, not directly taken from UKB (calculated with Dubois formula? and with weight)

# traits
traits_group = {
       'ascending_aortic': ['AAo_max_area', 'AAo_min_area', 'AAo_distensibility'] ,
       'descending_aortic': ['DAo_max_area', 'DAo_min_area', 'DAo_distensibility'] ,
       'left_atrium': ['LAV_max', 'LAV_min', 'LASV', 'LAEF'] ,
       'right_atrium': ['RAV_max', 'RAV_min', 'RASV', 'RAEF'] ,
       'left_ventricle': ['LVEDV', 'LVESV', 'LVSV', 'LVEF', 'LVCO', 'LVM', 'WT_Global', 'WT_Max_Global', 'Err_Global', 'Ell_Global', 'Ecc_Global'] ,
       'right_ventricle': ['RVEDV', 'RVESV', 'RVSV', 'RVEF'] ,
       'mean_WT': ['WT_AHA_1', 'WT_AHA_2', 'WT_AHA_3', 'WT_AHA_4', 'WT_AHA_5',
              'WT_AHA_6', 'WT_AHA_7', 'WT_AHA_8', 'WT_AHA_9', 'WT_AHA_10',
              'WT_AHA_11', 'WT_AHA_12', 'WT_AHA_13', 'WT_AHA_14', 'WT_AHA_15',
              'WT_AHA_16'] ,
       'max_WT': ['WT_Max_AHA_1', 'WT_Max_AHA_2', 'WT_Max_AHA_3', 'WT_Max_AHA_4', 'WT_Max_AHA_5',
              'WT_Max_AHA_6', 'WT_Max_AHA_7', 'WT_Max_AHA_8', 'WT_Max_AHA_9', 'WT_Max_AHA_10',
              'WT_Max_AHA_11', 'WT_Max_AHA_12', 'WT_Max_AHA_13', 'WT_Max_AHA_14', 'WT_Max_AHA_15',
              'WT_Max_AHA_16'] ,
       'radial_strain_rates': ['Err_AHA_1', 'Err_AHA_2', 'Err_AHA_3',
              'Err_AHA_4', 'Err_AHA_5', 'Err_AHA_6', 'Err_AHA_7', 'Err_AHA_8',
              'Err_AHA_9', 'Err_AHA_10', 'Err_AHA_11', 'Err_AHA_12', 'Err_AHA_13',
              'Err_AHA_14', 'Err_AHA_15', 'Err_AHA_16'] ,
       'circumferential_strain_rates': ['Ecc_AHA_1', 'Ecc_AHA_2', 'Ecc_AHA_3', 'Ecc_AHA_4', 'Ecc_AHA_5',
              'Ecc_AHA_6', 'Ecc_AHA_7', 'Ecc_AHA_8', 'Ecc_AHA_9', 'Ecc_AHA_10',
              'Ecc_AHA_11', 'Ecc_AHA_12', 'Ecc_AHA_13', 'Ecc_AHA_14', 'Ecc_AHA_15',
              'Ecc_AHA_16'] ,
       'longitudinal_strain_rates': ['Ell_1', 'Ell_2', 'Ell_3', 'Ell_4', 'Ell_5', 'Ell_6']
}